language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules

script:
  - npm test -- -u --coverage

install:
- npm install -q --no-color --no-progress

after_script:
 - npm run coveralls 
